### PR TITLE
Fast ending

### PR DESCRIPTION
**Pull request by omegaphoenix**
Fixed ending behavior for TCP FAST

### CODE REVIEW

**Comment by omegaphoenix** [comment]
@dqu123 @alphaz99 @nancyywen   Merge me! Happy Thanksgiving!  Good work, team!

**Comment by omegaphoenix** [comment]
@dqu123 @alphaz99 @nancyywen Bump.  David, do you want to add the latex files for the writeup to our repo or should we keep that separate?

**Comment by dqu123** [comment]
@omegaphoenix  Sorry about not responding. Github doesn't really notify you that much when you do the @ thing, which they should fix (/ I still need to find a good team organization software that I check often). I'm about to look at it. The LaTeX is in a overleaf link that I sent.

**Comment by dqu123** [comment]
Looks like it's working to me.

**Pull request merged**
