### PR TITLE
Better fix for bugs

### PR DESCRIPTION
**Pull request by alphaz99**
Much better fix for the bugs in link.py from https://github.com/BLQ-Software/black-widow/pull/15.

### CODE REVIEW

**Comment by alphaz99** [comment]
@dqu123, @omegaphoenix, can you guys take a look at this to make sure the logic is sound? It's much more clearer than the previous version of link.py and solves the edge cases as well.

**Comment by alphaz99** [comment]
@dqu123 should be fixed now

**Comment by alphaz99** [comment]
Takes 19.798 seconds to run, not including timeouts

**Comment by alphaz99** [comment]
Now takes 25 seconds to run

**Comment by dqu123** [comment]
Can we clean up the data files / logic for running that before committing those files?
Right now I think you've been commit some files with overwritten stuff.

**Comment by alphaz99** [comment]
That sound be fine, the link only has to worry about the two devices it is connected to

**Comment by dqu123** [comment]
But aren't you checking the source id, which is the overall flow source?

**Comment by alphaz99** [comment]
Yeah good point, I fixed that. It was fine before, looks like I changed it pretty recently. Link now checks the source of the device sending the packet.

**Comment by dqu123** [comment]
@alphaz99, @omegaphoenix How should I make reoccurring router events that eventually end (for dynamic routing, we'll need them to go until all the flows are done. Maybe the network can keep track of when the flows are done).

**Comment by alphaz99** [comment]
@dqu123 One option is to have the network create recurring router events depending on how many flows are done and the time.

**Comment by alphaz99** [comment]
Note: all Devices now have id as network_id. Otherwise it gets too complicated to figure out the name of the attribute and the earlier method was storing both a network_id and a host_id for example that were the same thing.

**Comment by alphaz99** [comment]
@dqu123 @omegaphoenix See https://github.com/BLQ-Software/black-widow/wiki/OOP-Guidelines

**Comment by alphaz99** [comment]
It should be fixed now

**Comment by alphaz99** [comment]
case1 still runs forever but thats a different issue

**Comment by dqu123** [comment]
That's because I haven't added the router events yet, since I'm deciding how to determine that all the flows are done since we haven't added that part into our network.

**Comment by alphaz99** [comment]
What do you think of my previous idea, where the network creates router events?

**Comment by dqu123** [comment]
I'm going to merge this now, because I think it improves the code. I got routing to work again, but the time it takes to run is pretty high so idk if that's problems with the flow or the links or the routers. See #17.

**Pull request merged**
