### PR TITLE
Refactoring all code

### PR DESCRIPTION
**Pull request by alphaz99**

### CODE REVIEW

**Comment by dqu123** [comment]
@omegaphoenix @alphaz99 I made a BlackWidow class, so look at
BlackWidow.record(data, data_type), and edit its docstring to whatever you want the file extensions to be for the log files (will be associated with a data_type). That way you can record different types of data differently.

**Comment by alphaz99** [comment]
@omegaphoenix it would be a good idea to separate our send() functions into poll() and send(). That way the network can poll links and flows to check if they are ready to send. The poll functions would then internally call send for each of these classes.
For example, the poll function for the link would both poll packets to be released into the link and packets to be released to a device.

**Comment by dqu123** [comment]
We should determine when we want to merge this / set a plan for this branch since it has
a pretty general name.

**Comment by omegaphoenix** [comment]
I'm going to merge and then create a new branch to fix some things in the flow code.

**Pull request merged**
