### PR TITLE
Documentation generation

### PR DESCRIPTION
**Pull request by dqu123**
It looks like one group used Sphinx for documentation. (I think it's a requirement to have documentation for the project). @alphaz99, @omegaphoenix @nancyywen 
See: http://black-widow.readthedocs.org/en/doc/

### CODE REVIEW

**Comment by dqu123** [comment]
@alphaz99 Does this look right? Also any tips for using Sphinx?

**Comment by dqu123** [comment]
Also, @omegaphoenix, @nancyywen, we should familiarize ourselves with Sphinx documentation, so we can document our code in a consistent style.

**Comment by nancyywen** [comment]
@dqu123 Ok, I'll review the Sphinx documentation right now.

**Comment by alphaz99** [comment]
Looks good to me, what did you run to generate the documentation? sphinx-apidoc -o [output_dir] [input_dir] -F

**Pull request merged**
